config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
                                            sign_in: 'login',
                                            sign_up: 'register',
                                            sign_out: 'logout'
                                          }
  resources :companies
  resources :kinds

  # get 'home/index'
  # get 'home/chuchu', to: 'home#index'
  root 'home#index'

  resources :addresses
  resources :phones
  resources :contacts do
    collection do
      get :search
      get :search_result
    end
  end
  resources :kinds, except: [:destroy]
  # resources(:kinds, {:except => [:destroy, :update, :edit]})

  resources :pets, only: [:index, :show, :new, :edit]
  # resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  validates_presence_of :name
  validates :name, uniqueness: true
  validates :name, length: {in: 6..200}

  has_many :contacts
  has_many :phones, through: :contacts
  has_many :addresses, through: :contacts
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind
  belongs_to :company
  has_one :address
  has_many :phones
  has_and_belongs_to_many :users

  def to_s
    self.name
  end
end

app/models/kind.rb
class Kind < ApplicationRecord
  def to_s
    self.description
  end

  has_many :contacts
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :person
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :contacts

  validates_presence_of :name
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def search
    @kinds = Kind.order(:description)
  end

  def search_result
    @kinds = Kind.order(:description)

    @search_params = params[:search]
    kind = Kind.find_by_id @search_params[:kind_id]
    @contacts = Contact
                  .includes(:kind, :company)
                  .where('name like ?', "%#{@search_params[:name]}%")
                  .order(:name)
    @contacts = @contacts.where(kind: kind) if kind

    render 'search'
  end

  # GET /contacts
  # GET /contacts.json
  def index
    order = params[:order] || 'asc'
    @new_order = order == 'desc' ? 'asc' : 'desc'
    @contacts = Contact
                  .includes(:kind, :company)
                  .order(name: order)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :remark, :kind_id, :company_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /kinds
  # GET /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1
  # GET /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds
  # POST /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1
  # PATCH/PUT /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kind_params
      params.require(:kind).permit(:description)
    end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  # GET /pets
  # GET /pets.json
  def index
    @pets = Pet.all
  end

  # GET /pets/1
  # GET /pets/1.json
  def show
  end

  # GET /pets/new
  def new
    @pet = Pet.new
  end

  # GET /pets/1/edit
  def edit
  end

  # POST /pets
  # POST /pets.json
  def create
    @pet = Pet.new(pet_params)

    respond_to do |format|
      if @pet.save
        format.html { redirect_to @pet, notice: 'Pet was successfully created.' }
        format.json { render :show, status: :created, location: @pet }
      else
        format.html { render :new }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pets/1
  # PATCH/PUT /pets/1.json
  def update
    respond_to do |format|
      if @pet.update(pet_params)
        format.html { redirect_to @pet, notice: 'Pet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pet }
      else
        format.html { render :edit }
        format.json { render json: @pet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pets/1
  # DELETE /pets/1.json
  def destroy
    @pet.destroy
    respond_to do |format|
      format.html { redirect_to pets_url, notice: 'Pet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pet
      @pet = Pet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pet_params
      params.require(:pet).permit(:name, :kind, :person_id)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :remark %>
    <%= f.association :kind %>
    <%= f.association :comapny %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="page-header">
  <%= link_to contacts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @contact, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing contact</h1>
</div>

<%= render 'form' %>

app/views/contacts/index.html.erb
<div class="page-header">
  <h1>Listing contacts</h1>
  <%= link_to new_contact_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Contact
  <% end %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th><%= link_to 'Name', order: @new_order %></th>
            <th>Email</th>
            <th>Remark</th>
            <th>Kind</th>
            <th>Company</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
            <td><%= contact.name %></td>
            <td><%= contact.email %></td>
            <td><%= contact.remark %></td>
            <td><%= contact.kind.description %></td>
            <td><%= contact.company.name %></td>
            <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/contacts/new.html.erb
<div class="page-header">
  <%= link_to contacts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New contact</h1>
</div>

<%= render 'form' %>

app/views/contacts/search.html.erb
<%= simple_form_for :search, url: search_result_contacts_path, method: :get do |f| %>
  <%= f.input :name, input_html: { value: @search_params ? @search_params[:name] : '' } %>
  <%= f.input :kind_id, collection: @kinds, selected: (@search_params[:kind_id] if @search_params), include_blank: true %>
  <%= f.button :submit, 'Buscar', class: 'btn-primary' %>
<% end %>

<% if @contacts %>
  <div class="table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
              <th><%= link_to 'Name', order: @new_order %></th>
              <th>Email</th>
              <th>Remark</th>
              <th>Kind</th>
              <th>Company</th>
              <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @contacts.each do |contact| %>
          <tr>
              <td><%= contact.name %></td>
              <td><%= contact.email %></td>
              <td><%= contact.remark %></td>
              <td><%= contact.kind.description %></td>
              <td><%= contact.company.name %></td>
              <td><%= link_to 'Show', contact %></td>
          <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
          <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/contacts/show.html.erb
<div class="page-header">
  <%= link_to contacts_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_contact_path(@contact), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show contact</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @contact.name %></dd>

  <dt>Email:</dt>
  <dd><%= @contact.email %></dd>

  <dt>Remark:</dt>
  <dd><%= @contact.remark %></dd>

  <dt>Kind:</dt>
  <dd><%= @contact.kind.description %></dd>

  <dt>Company:</dt>
  <dd><%= @contact.company.name %></dd>

</dl>