config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
                                            sign_in: 'login',
                                            sign_up: 'register',
                                            sign_out: 'logout'
                                          }
  resources :companies
  resources :kinds

  # get 'home/index'
  # get 'home/chuchu', to: 'home#index'
  root 'home#index'

  resources :addresses
  resources :phones
  resources :contacts do
    collection do
      get :search
      get :search_result
    end
  end
  resources :kinds, except: [:destroy]
  # resources(:kinds, {:except => [:destroy, :update, :edit]})

  resources :pets, only: [:index, :show, :new, :edit]
  # resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  validates_presence_of :name
  validates :name, uniqueness: true
  validates :name, length: {in: 6..200}

  has_many :contacts
  has_many :phones, through: :contacts
  has_many :addresses, through: :contacts
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :kind
  belongs_to :company
  has_one :address
  has_many :phones
  has_and_belongs_to_many :users

  def to_s
    self.name
  end
end

app/models/kind.rb
class Kind < ApplicationRecord
  def to_s
    self.description
  end

  has_many :contacts
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :person
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_and_belongs_to_many :contacts

  validates_presence_of :name
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RailsContacts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Empresas', companies_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Tipos de Contato', kinds_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Contatos', contacts_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Telefones', phones_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Endereços', addresses_path, class: 'nav-link' %>
            </li>
          </ul>

          <ul class="navbar-nav mr-0">
            <li class="nav-item">
              <% if user_signed_in? %>
                <%= link_to "#{current_user.name} (Deslogar)", destroy_user_session_path, method: :delete, class: 'nav-link' %>        
              <% else %>
                <%= link_to 'Login', new_user_session_path, class: 'nav-link'  %>
              <% end %>
            </li>
          </ul>

        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= msg %>
        <% end %>
      <% end %>
      
      <%= yield %>
    </div>
  </body>
</html>